### ISSUE TITLE
Fix build failure

### ISSUE THREAD

**Issue by KirstieJane** [MELDProject/MELDProject.github.io#1]
Hi @sophieadler!

Those error messages from jekyll and github pages are AWFUL, right?! "Page build failure. The end. Go figure it all out yourself now". 😡

I've just spent an unreasonable amount of time playing around with this because (as @islast will know) these are the sorts of [nerd sniping](https://xkcd.com/356/) tasks that I just can't disengage from.

I think the problem is that you have posts in the template folder that no longer have images associated with them. Basically if you delete that `/_posts/templates` folder you should fix the problem. Alternatively, keep the image files they're lookign for in your `images` folder so you can keep the templates for future reference.

I have to make a talk now but I'll try to submit a pull request during the conference. ✨

**Comment by MELDProject** [comment]
Hi @KirstieJane !

Thanks so much!! I did as you suggested and page builds are working again. Woohoo. Out of interest how did you work out what the problem was?

**Comment by KirstieJane** [comment]
So - I couldn't figure out the bug 😭 BUT I did manage to keep the templates which I think is quite useful if you want to use them going forwards 😄. I've also added in travis CI and made a couple of small updates in #2 too ✨

**Comment by KirstieJane** [comment]
Fixed! Website looks great!
